services:
  lastsave-app:
    image: ghcr.io/zor07/lastsave-platform:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8581:8080"
    env_file:
      - .env
    environment:
      JAVA_TOOL_OPTIONS: "-DsocksProxyHost=host.docker.internal -DsocksProxyPort=1080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - lastsave-db
    volumes:
      - /var/log/lastsave:/app/logs

  lastsave-db:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:8580:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - lastsave_pgdata:/var/lib/postgresql/data

volumes:
  lastsave_pgdata:
